---
- name: TEST CONFIG INTERFACE
  hosts: cisco
  gather_facts: no
  connection: local

  tasks:  
  - name: CONFIG INTERFACE L2
    ios_interface:
      authorize: True
      auth_pass: cisco
      name: "{{ INTF }}"
      enabled: True
  
  - name: CONFIG INTERFACE L3
    ios_l3_interface:
      authorize: True
      auth_pass: cisco
      name: "{{ INTF }}"
      ipv4: "{{ IPMASK }}"
    
    register: result

  #- debug: msg="{{ result.stdout }}"
